export const genreFilter = {
  defaultValue: { value: "", text: "All" },
  label:"Genre:",
  options: [
    { text: "Action", value: "action" },
    { text: "Adventure", value: "adventure" },
    { text: "Animation", value: "animation" },
    { text: "Biography", value: "biography" },
    { text: "Comedy", value: "comedy" },
    { text: "Documentary", value: "documentary" },
    { text: "Drama", value: "drama" },
    { text: "Family", value: "family" },
    { text: "Fantasy", value: "fantasy" },
    { text: "Film-Noir", value: "film-noir" },
    { text: "History", value: "history" },
    { text: "Horror", value: "horror" },
    { text: "Music", value: "music" },
    { text: "Musical", value: "musical" },
    { text: "Mystery", value: "mystery" },
    { text: "Romance", value: "romance" },
    { text: "Sci-Fi", value: "sci-fi" },
    { text: "Short", value: "short" },
    { text: "Superhero", value: "superhero" },
    { text: "Thriller", value: "thriller" },
    { text: "War", value: "war" },
    { text: "Western", value: "western" },
  ],
};
